front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
front_sitemap:
    path:     /sitemap.xml
    defaults: { _controller: FrontBundle:Default:sitemaps }
flux_rss:
    path:     /rss
    defaults: { _controller: FrontBundle:Default:rss }
front_category:
    path: /{locale}/category/{slug}
    defaults : { _controller: FrontBundle:Category:index }
ramadan:
    path: /{locale}/ramadan{year}
    defaults : { _controller: FrontBundle:Category:ramadan }
front_article:
    path: /{locale}/{categoryname}/{year}/{month}/article/{slug}/
    defaults : { _controller: FrontBundle:Article:index }
search_recipe:
    path: /recherche
    defaults : { _controller: FrontBundle:Category:search }