front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
front_category:
    path: /{locale}/category/{slug}.html
    defaults : { _controller: FrontBundle:Category:index }