zenstruck_backup:
    namers:

        # Prototype
        name:
            simple:
                name:                 backup
            timestamp:
                format:               YmdHis
                prefix:               'tounsia'
                timezone:             ~
    processors:
        # Prototype
        name:
            zip:
                options:              '-r'
                timeout:              300

    sources:

        # Prototype
        name:
            mysqldump:
                database:             '%database_name%'
                host:                 '%database_host%'
                user:                 '%database_user%'
                password:             '%database_password%'
                ssh_host:             null
                ssh_user:             null
                ssh_port:             22
                timeout:              700

    destinations:
        s3:
            s3cmd:
                bucket: "s3://foobar/backups"
    profiles:

        # Prototype
        name:
            scratch_dir:          '%kernel.cache_dir%/backup'
            sources:              [database] # Required, can be a string
            namer:                daily
            processor:            zip
            destinations:         [s3] # Required, can be a string