zenstruck_backup:
    sources:
        database:
            mysqldump:
                database: '%database_name%'
        files:
            rsync:
                source: "%kernel.root_dir%/../backup"
                additional_options:
                    - --exclude=_cache/
  # Prototype
        name:
            mysqldump:
                database:             '%database_name%'
                host:                 '%database_host%'
                user:                 '%database_user%'
                password:             '%database_password%'
                timeout:              300
    namers:
        daily:
            timestamp:
                format: d
                prefix: tounsia-
        snapshot:
            timestamp:
                prefix: tounsia-
    processors:
        zip: { zip: ~ }
    destinations:
        s3:
            s3cmd:
                bucket: "s3://foobar/backup/tounsia-{day-of-month}"
    profiles:
        daily:
            scratch_dir: "%kernel.root_dir%/cache/backup"
            sources: [database]
            namer: daily
            processor: zip
            destinations: [s3]