zenstruck_backup:
    sources:
        database:
            mysqldump:
                database: '%database_name%'

    namers:
        daily:
            timestamp:
                format: d
                prefix: mysite-
        snapshot:
            timestamp:
                prefix: mysite-
    processors:
        zip: { zip: ~ }
    destinations:
        s3:
        #    s3cmd:
        #        bucket: "s3://foobar/backups"
            stream:
                directory:     "/backup"
    profiles:
        daily:
            scratch_dir: "%kernel.root_dir%/cache/backup"
            sources: [database]
            namer: daily
            processor: zip
            destinations: [s3]