liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        category_page:
            quality: 100
            filters:
                thumbnail: { size: [796, 321], mode: outbound }
        galery:
            quality: 100
            filters:
                thumbnail: { size: [220, 200], mode: outbound }