liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        category_page:
            quality: 75
            filters:
                thumbnail: { size: [796, 321], mode: outbound }