liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        category_page:
            quality: 100
            filters:
                upscale: { min: [796, 321] }
                thumbnail: { size: [796, 321], mode: outbound , format: png  }
        galery:
            quality: 100
            filters:
                upscale: { min: [220, 220] }
                thumbnail: { size: [220, 220], mode: inset  , format: png }
        hug:
            quality: 100
            filters:
                upscale: { min: [730, 320] }
                thumbnail: { size: [730, 320], mode: inset  , format: png }
        hug2:
            quality: 100
            filters:
                upscale: { min: [730, 480] }
                thumbnail: { size: [730, 480], mode: inset  , format: png }
        cuisine1:
            quality: 100
            filters:
                upscale: { min: [540, 335] }
                thumbnail: { size: [540, 335], mode: inset  , format: png }
        cuisine2:
            quality: 100
            filters:
                upscale: { min: [160, 120] }
                thumbnail: { size: [160, 120], mode: inset  , format: png }