liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        category_page:
            quality: 100
            filters:
                upscale: { min: [796, 321] }
                thumbnail: { size: [796, 321], mode: inset , format: png  }
        galery:
            quality: 100
            filters:
                upscale: { min: [220, 220] }
                thumbnail: { size: [220, 220], mode: inset  , format: png }