sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.block.service.posts: ~
        sonata.block.service.tablecompare: ~
        sonata.block.service.month: ~
        sonata.block.service.monthuser: ~
        sonata.block.service.viewuser: ~
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    impersonating:
        route:                page_slug
        parameters:           { path: / }

    class:                  # Entity Classes
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group

    admin:                  # Admin Classes
        user:
            class:          Application\Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
sonata_admin:
    templates:
        layout:               :Sonata:standard_layout.html.twig
        dashboard:            :Core:dashboard.html.twig
    title:                'Tounsianet'
    title_logo:           public/logo.png

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.block.service.posts, settings: { template: 'PostBundle:Block:Posts.html.twig'  } }
            - { position: right, type: sonata.block.service.tablecompare, settings: { template: 'PostBundle:Block:table.html.twig'  } }
            - { position: left, type: sonata.block.service.month, settings: { template: 'PostBundle:Block:month.html.twig'  } }
            - { position: left, type: sonata.block.service.monthuser, settings: { template: 'PostBundle:Block:monthuser.html.twig'  } }
            - { position: right, type: sonata.block.service.viewuser, settings: { template: 'PostBundle:Block:viewuser.html.twig'  } }
        groups:

            article:
                label: Article
                icon: '<i class="fa fa-file-text" aria-hidden="true"></i>'
                items:
                    - admin.posts
            Configuration:
                label: Users
                icon: '<i class="fa fa-cogs"></i>'
                items:
                    - admin.category
                    - sonata.user.admin.user
                    - sonata.user.admin.group