sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.block.service.posts: ~
        sonata.block.service.myposts: ~
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    impersonating:
        route:                page_slug
        parameters:           { path: / }

    class:                  # Entity Classes
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group

    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
sonata_admin:

    title:                'Tounsianet'
    title_logo:           public/logo.png

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.block.service.posts, settings: { template: 'PostBundle:Block:Posts.html.twig'  } }
            - { position: right, type: sonata.block.service.myposts, settings: { template: 'PostBundle:Block:myPosts.html.twig'  } }
            #- { position: left, type: sonata.block.service.status, settings: { title: Project Status }}
            #- { position: right,  type: sonata.admin.block.admin_list, settings: { groups: [utilisateur, Configuration] } }
            #- { position: left, type: sonata.admin.block.service.status, settings: { groups: [Projects] } }
        groups:

            article:
                label: Article
                icon: '<i class="fa fa-home"></i>'
                items:
                    - admin.category
                    - admin.posts
            utilisateur:
                label: Users
                icon: '<i class="fa fa-users"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group