<?php

namespace PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewsRepository extends EntityRepository
{
    public function findpopular(){
        $dt = new \DateTime();
        $dt->modify("-1 week");
        $query = $this->getEntityManager()
            ->createQuery("select p  from
                                PostBundle\Entity\Views as p where 
                                 p.dv >='".$dt->format('Y-m-d')."'");
        return $query->getResult();

    }
}
