post_homepage:
    path:     /hello/{name}
    defaults: { _controller: PostBundle:Default:index }
jsonlinks:
    path:     /jsonlinks
    defaults: { _controller: PostBundle:Default:linkpost }
jsonyoutube:
    path:     /youtube
    defaults: { _controller: PostBundle:Default:youtube }
pie_charts:
    path:     /pieCharts/{id}
    defaults: { _controller: PostBundle:Default:pieCharts }
editingredient:
    path:     /editingredients
    defaults: { _controller: PostBundle:Default:listtoUpdate }

image:
    path: /admin/image/{id}
    defaults : { _controller: PostBundle:Default:image }
twitter_share:
    path: /admin/sharetwitter/{id}
    defaults : { _controller: PostBundle:Default:shareTwitter }