services:
#    post.example:
#        class: PostBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    sonata.block.service.posts:
        class: PostBundle\Block\PostsBlockService
        arguments: [ "sonata.block.service.posts", @templating, @service_container ]
        tags:
            - { name: sonata.block }
    sonata.block.service.share:
        class: PostBundle\Block\ShareBlockService
        arguments: [ "sonata.block.service.posts", @templating, @service_container ]
        tags:
            - { name: sonata.block }
    sonata.block.service.month:
        class: PostBundle\Block\MonthsBlockService
        arguments: [ "sonata.block.service.month", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.short1:
        class: PostBundle\Block\ShortBlockService
        arguments: [ "sonata.block.service.short1", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.viewweek:
        class: PostBundle\Block\ViewWeekBlockService
        arguments: [ "sonata.block.service.viewweek", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.alexa:
        class: PostBundle\Block\AlexaBlockService
        arguments: [ "sonata.block.service.alexa", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.monthuser:
        class: PostBundle\Block\MonthsUsersBlockService
        arguments: [ "sonata.block.service.monthuser", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.viewuser:
        class: PostBundle\Block\ViewUsersBlockService
        arguments: [ "sonata.block.service.viewuser", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }

    sonata.block.service.tablecompare:
        class: PostBundle\Block\TableBlockService
        arguments: [ "sonata.block.service.tablecompare", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.refer:
        class: PostBundle\Block\ReferBlockService
        arguments: [ "sonata.block.service.refer", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }

    sonata.block.service.viewposts:
        class: PostBundle\Block\ViewPostsBlockService
        arguments: [ "sonata.block.service.viewposts", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.viewsmonths:
        class: PostBundle\Block\ViewMonthsBlockService
        arguments: [ "sonata.block.service.viewsmonths", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }


    Tools.utils:
        class: PostBundle\Services\NewsServices


    admin.tasks:
        class: PostBundle\Admin\TasksAdmin
        arguments: [~, PostBundle\Entity\Tasks, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Liste des tâches', icon:'<i class="fa fa-envelope"></i>' }
    admin.views:
        class: PostBundle\Admin\ViewsAdmin
        arguments: [~, PostBundle\Entity\Views, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Views', icon:'<i class="fa fa-eye"></i>' }
    admin.refer:
            class: PostBundle\Admin\ReferAdmin
            arguments: [~, PostBundle\Entity\Refer, ~] #MailingBundle:CRUD
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'SIte référant', icon:'<i class="fa fa-eye"></i>' }
    admin.allowip:
        class: PostBundle\Admin\AllowIpAdmin
        arguments: [~, PostBundle\Entity\AllowIp, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Liste des ip valid', icon:'<i class="fa fa-envelope"></i>' }
    admin.alexa:
        class: PostBundle\Admin\AlexaAdmin
        arguments: [~, PostBundle\Entity\Alexa, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Alexa', icon:'<i class="fa fa-envelope"></i>' }
    admin.category:
        class: PostBundle\Admin\CategoryAdmin
        arguments: [~, PostBundle\Entity\Category, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Catégories', icon:'<i class="fa fa-envelope"></i>' }
        calls:
            #- [ setTemplate, [edit, MainFactBundle:Projects:edit.html.twig]]
    admin.posts:
        class: PostBundle\Admin\PostsAdmin
        arguments: [~, PostBundle\Entity\Post, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Articles', icon:'<i class="fa fa-envelope"></i>' }
        calls:
            - [ setTemplate, [edit, PostBundle:Post:edit.html.twig]]
    admin.search:
        class: PostBundle\Admin\SearchAdmin
        arguments: [~, PostBundle\Entity\Search, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Search'}
    admin.setings:
        class: PostBundle\Admin\SettingsAdmin
        arguments: [~, PostBundle\Entity\Settings, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Settings'}

    admin.chaines:
        class: PostBundle\Admin\ChainesAdmin
        arguments: [~, PostBundle\Entity\Chaines, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "WebTv" ,label: 'Chaines Youtube'}
