services:
#    post.example:
#        class: PostBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    sonata.block.service.posts:
        class: PostBundle\Block\PostsBlockService
        arguments: [ "sonata.block.service.posts", @templating, @service_container ]
        tags:
            - { name: sonata.block }
    sonata.block.service.month:
        class: PostBundle\Block\MonthsBlockService
        arguments: [ "sonata.block.service.month", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.alexa:
        class: PostBundle\Block\AlexaBlockService
        arguments: [ "sonata.block.service.alexa", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.monthuser:
        class: PostBundle\Block\MonthsUsersBlockService
        arguments: [ "sonata.block.service.monthuser", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }
    sonata.block.service.viewuser:
        class: PostBundle\Block\ViewUsersBlockService
        arguments: [ "sonata.block.service.viewuser", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }

    sonata.block.service.tablecompare:
        class: PostBundle\Block\TableBlockService
        arguments: [ "sonata.block.service.tablecompare", @templating, @doctrine.orm.entity_manager ]
        tags:
            - { name: sonata.block }


    Tools.utils:
        class: PostBundle\Services\NewsServices


    admin.alexa:
        class: PostBundle\Admin\AlexaAdmin
        arguments: [~, PostBundle\Entity\Alexa, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Alexa', icon:'<i class="fa fa-envelope"></i>' }
    admin.category:
        class: PostBundle\Admin\CategoryAdmin
        arguments: [~, PostBundle\Entity\Category, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Catégories', icon:'<i class="fa fa-envelope"></i>' }
        calls:
            #- [ setTemplate, [edit, MainFactBundle:Projects:edit.html.twig]]
    admin.posts:
        class: PostBundle\Admin\PostsAdmin
        arguments: [~, PostBundle\Entity\Post, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Articles', icon:'<i class="fa fa-envelope"></i>' }
        calls:
            - [ setTemplate, [edit, PostBundle:Post:edit.html.twig]]
    admin.search:
        class: PostBundle\Admin\SearchAdmin
        arguments: [~, PostBundle\Entity\Search, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Search'}
